<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Acer" failures="1" tests="3" name="TestPack.Login" time="63.754" errors="0" timestamp="2023-10-14T19:30:59 IST" skipped="0">
  <testcase classname="TestPack.Login" name="withValidCredential" time="27.324">
    <failure message="expected [https://www.amazon.in/?ref_=nav_ya_signin] but found [https://www.amazon.in/ap/cvf/request?arb=3afc09bc-90b4-489d-b1a6-000c8364678c]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.amazon.in/?ref_=nav_ya_signin] but found [https://www.amazon.in/ap/cvf/request?arb=3afc09bc-90b4-489d-b1a6-000c8364678c]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestPack.Login.withValidCredential(Login.java:94)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </failure>
  </testcase> <!-- withValidCredential -->
  <system-out/>
  <testcase classname="TestPack.Login" name="withValidEmailAndWrongPassword" time="16.666"/>
  <system-out/>
  <testcase classname="TestPack.Login" name="withInValidEmail" time="19.764"/>
  <system-out/>
</testsuite> <!-- TestPack.Login -->
